name: Test ENV passing
on:
  workflow_call:
    inputs:
      env_file:
        description: "All env variables"
        required: false
        type: string
        default: ""

jobs:
  test-env:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: log passed env's
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ inputs.env_file }}
