name: Test ENV passing
on:
  workflow_call:
    inputs:
      env_file:
        description: "All env variables"
        required: false
        type: string
        default: ""

jobs:
  test-env:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository (clone the repo for use)
        uses: actions/checkout@v3

      - name: test-json
        run: |
          json=${{ fromJson(inputs.env_file) }}
          echo $json

      - name: create file in action
        run: |
          echo "${{ inputs.env_file }}" >> .env

      - name: log input env vars
        uses: ./actions/env-logger
        with:
          env_file: "${{ inputs.env_file }}"

      - name: log env file
        run: |
          cat .env

      - name: list files
        run: ls -a
