name: Test ENV passing
on:
  workflow_call:
    inputs:
      env_file:
        description: "All env variables"
        required: false
        type: string
        default: ""

jobs:
  test-env:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: create file in action
        run: |
          echo "${{ inputs.env_file }}" >> .env

      - name: log env file
        run: |
          cat .env
