name: TestCase 1 - Passing ENV
on:
  push: 
    branches:
      - main
  
jobs:
  test-passed-env:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      env_file: |
        test_env_1: |
          KEY1: 'VAL1'
          KEY2: 'VAL2'
        test_env_2: |
          KEY3: 'VAL3'
          KEY4: 'VAL4'
